version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "amirtheahmed"
    reviewers:
      - "amirtheahmed"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "amirtheahmed"
    reviewers:
      - "amirtheahmed"
