version: '3.8'

services:
  vartur-mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: vartur_docker_db
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - internal-net
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_APP_API_URL=http://fastify-vuejs-backend:3000/api
        - VITE_APP_API_UPLOAD_URL=http://fastify-vuejs-backend:3000
    container_name: frontend
    restart: unless-stopped
    environment:
      PORT: 4173
    ports:
      - "4173:4173"
    networks:
      - internal-net
    depends_on:
      - vartur-backend
  vartur-backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=mysql://root:123456789@vartur-mysqldb/vartur_docker_db
    depends_on:
      - vartur-mysqldb
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
