version: '3.8'

services:
  fastify-vuejs-mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fastify_vuejs_docker_db
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - fastify-vuejs-net

  fastify-vuejs-frontend:
    container_name: fastify-vuejs-frontend
    image: amirtheahmed/fastify-vuejs-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastify-vuejs-frontend.rule=Host(`fastify-vuejs-app.amirtheahmed.dev`, `www.fastify-vuejs-app.amirtheahmed.dev`)"
      - "traefik.http.routers.fastify-vuejs-frontend.entrypoints=https"
      - "traefik.http.services.fastify-vuejs-frontend.loadbalancer.server.port=4173"
    restart: unless-stopped
    ports:
      - "4173:4173"
    networks:
      - fastify-vuejs-net
      - proxy
    depends_on:
      - fastify-vuejs-backend

  fastify-vuejs-backend:
    container_name: fastify-vuejs-backend
    image: amirtheahmed/fastify-vuejs-backend:latest
    environment:
      - DATABASE_URL=mysql://root:123456789@fastify-vuejs-mysqldb/fastify_vuejs_docker_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastify-vuejs-backend.rule=Host(`fastify-vuejs-api.amirtheahmed.dev`, `www.fastify-vuejs-api.amirtheahmed.dev`)"
      - "traefik.http.routers.fastify-vuejs-backend.entrypoints=https"
      - "traefik.http.services.fastify-vuejs-backend.loadbalancer.server.port=3000"  
    ports:
      - "3000:3000"
    networks:
      - fastify-vuejs-net
      - proxy  
    depends_on:
      - fastify-vuejs-mysqldb

networks:
  fastify-vuejs-net:
    driver: bridge
  proxy:
    external: true
