name: Push

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: 🐳 Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get repository info
        uses: gacts/github-slug@v1
        id: slug

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build & Push Docker image for frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ steps.slug.outputs.version }}"
            DATE_CREATED=${{ steps.date.outputs.date }}
          tags: |
            amirtheahmed/fastify-vuejs-frontend:${{ steps.slug.outputs.version }}
            amirtheahmed/fastify-vuejs-frontend:latest

      - name: Build & Push Docker image for backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ steps.slug.outputs.version }}"
            DATE_CREATED=${{ steps.date.outputs.date }}
          tags: |
            amirtheahmed/fastify-vuejs-backend:${{ steps.slug.outputs.version }}
            amirtheahmed/fastify-vuejs-backend:latest      

  deploy:
    name: 🐳 Deploy Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sleep for 30 seconds
        run: sleep 20

      - name: Setup SSH & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull amirtheahmed/fastify-vuejs-frontend:latest &&
            docker pull amirtheahmed/fastify-vuejs-backend:latest &&
            cd /home/amirtheahmed/apps/fastify-vuejs-fullstack-app &&
            docker-compose pull &&
            docker-compose down &&
            docker-compose up --build -d    

permissions:
  security-events: write
  contents: write
  id-token: write
